#ifndef ENGINE_DEBUG_CATEGORY_H
#define ENGINE_DEBUG_CATEGORY_H

#define ENGINE_DEBUG_CATEGORY_FIRST 32

typedef enum
{
    DEBUG_CAT_RENDERER = ENGINE_DEBUG_CATEGORY_FIRST,
    DEBUG_CAT_MODEL,
    DEBUG_CAT_ANIMATION,
    DEBUG_CAT_CONSOLE,
    DEBUG_CAT_VALIDATION,
    ENGINE_DEBUG_CATEGORY_END,
} engine_debug_category_t;

#endif
