#ifndef DEBUG_CATEGORY_H
#define DEBUG_CATEGORY_H

#define GAME_DEBUG_CATEGORY_FIRST 64

typedef enum
{
    DEBUG_CAT_PROTOCOL = GAME_DEBUG_CATEGORY_FIRST,
    DEBUG_CAT_CLIENT,
    DEBUG_CAT_SERVER,
    DEBUG_CAT_LOS,
    DEBUG_CAT_LEVEL_GEN,
} game_debug_category_t;

#endif
